### PR TITLE
fix(clerk-react): Memoize useAuth.getToken and useAuth.signOut

### LINKED ISSUE #201: getToken changes after each render
- [X] Review the documentation: https://docs.clerk.dev/
- [X] Search for existing issues: https://github.com/clerkinc/javascript/issues
- [X] Go through package changelog files.
- [ ] Provide the Frontend API key from your application dashboard.

## Package + Version

- [ ] `@clerk/clerk-js`
- [X] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend-core`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/edge`
- [ ] other:

### Version:

```
^3.2.7
```

### Browser/OS

`Chrome latest`

## Description

We started migrating to v3 and noticed `getToken` from `useAuth` function identity is not stable and as a result changes after each re-render.

This causes the the app to go into infinite loop when `getToken` is used in the dependancy array of something like `useEffect`.
Usage Snippet:
image

A workaround is to remove it from the dependancy array, however that does not make eslint happy
image

It would be ideal if `getToken` can be made stable as it was in v2.

### PR DESCRIPTION
**Pull request by nikosdouvlis**
## Type of change

- [ ] 🐛 Bug fix
- [ ] 🌟 New feature
- [ ] 🔨 Breaking change
- [ ] 📖 Refactoring / dependency upgrade / documentation
- [ ] other:

## Packages affected

- [ ] `@clerk/clerk-js`
- [ ] `@clerk/clerk-react`
- [ ] `@clerk/nextjs`
- [ ] `@clerk/remix`
- [ ] `@clerk/types`
- [ ] `@clerk/themes`
- [ ] `@clerk/localizations`
- [ ] `@clerk/clerk-expo`
- [ ] `@clerk/backend`
- [ ] `@clerk/clerk-sdk-node`
- [ ] `@clerk/shared`
- [ ] `@clerk/fastify`
- [ ] `gatsby-plugin-clerk`
- [ ] `build/tooling/chore`

## Description

- [ ] `npm test` runs as expected.
- [ ] `npm run build` runs as expected.

Memoize the values of useAuth getToken and signOut

Closes #201
Closes #455

### CODE REVIEW

File: packages/react/src/hooks/utils.ts [hunk 1]
```diff
@@ -15,20 +15,22 @@ const clerkLoaded = (isomorphicClerk: IsomorphicClerk) => {
...
  */
-export const createSignOut =
-  (isomorphicClerk: IsomorphicClerk) =>
-  async (...args: any) => {
+export const createSignOut = (isomorphicClerk: IsomorphicClerk) => {
+  return async (...args: any) => {
     await clerkLoaded(isomorphicClerk);
     return isomorphicClerk.signOut(...args);
   };
+};
```
Comment (dimkl) [inline packages/react/src/hooks/utils.ts:36]: ❓ this changes are all related to code styling. Right?

File: packages/react/src/isomorphicClerk.ts [hunk 2]
```diff
@@ -251,7 +251,6 @@ export default class IsomorphicClerk {
   get session(): ActiveSessionResource | undefined | null {
     if (this.clerkjs) {
       return this.clerkjs.session;
-      // TODO: add ssr condition
```
Comment (dimkl) [inline packages/react/src/isomorphicClerk.ts:254]: ❓  why did we remove this?

**Review by dimkl — APPROVED** [review]

File: packages/react/src/hooks/utils.ts (hunk 1 above)
Comment (nikosdouvlis) [reply packages/react/src/hooks/utils.ts:36]: Correct! I'd argue it's slightly easier to parse the returned function in this case but that's personal preference of course
